/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AnthropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "DeploymentQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "DocumentQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "JobQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "NextAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NextAuthUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenaiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "WebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "WorkosApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WorkosClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WorkosCookiePassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WorkosRedirectUri": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}